name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100  
    - name: clean
      run: dotnet clean -c Release
    - name: build
      run: dotnet build
    - name: generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}       
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: dotnet pack
      run: dotnet pack ./Cashwu.AspNetCore.Redis/Cashwu.AspNetCore.Redis.csproj -c Release -o ./release
    - name: nuget publish
      if: github.ref == 'refs/heads/master'
      continue-on-error: true
      run: |
        dotnet nuget push ./release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
